joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

mobile_base_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  wheel_separation: 0.5
  wheel_radius: 0.1
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.01, 0.01, 0.01]

joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: 'joint1'
  pid: {p: 100.0, i: 0.01, d: 10.0}

